/**
 * A single simulated or live trade generated by the strategy.
 */
export interface Trade {
  id: string; // UUID or timestamp+symbol key
  symbol: string;
  side: 'long' | 'short' | 'flat';
  size: number; // Position size (e.g. shares or notional %)
  entryTs: string;
  entryPx: number;
  exitTs?: string;
  exitPx?: number;
  pnl?: number; // Realized PnL after costs
  reason: 'signal' | 'stop' | 'tp' | 'timeout'; // Why the trade closed
  vendor?: 'polygon' | 'providerB'; // Data vendor used
}
